ks44team03/pom.xml, ks44team03/src/main/java/ks44team03/admin/controller/MainController.java, ks44team03/src/main/resources/templates/fragments/footer.html, ks44team03/src/main/resources/templates/fragments/head.html, ks44team03/src/main/resources/templates/fragments/header.html, ks44team03/src/main/resources/templates/layout/mypage.html, ks44team03/src/main/resources/templates/myPage/mypage.html
author: 이국현
작업 내용 : head파일 추가, layout으로 마이페이지 레이아웃 만듦
=> [ks44team03] : 레이아웃 정리

ks44team03/src/main/java/ks44team03/user/controller/MypageController.java, ks44team03/src/main/resources/templates/fragments/footer.html, ks44team03/src/main/resources/templates/fragments/header.html, ks44team03/src/main/resources/templates/myPage/mypage.html
author : 이국현
file : header.html , footer.html
detail : mypage 실행 중 양식 깨짐으로 다시 수정
=> [ks44team03] : fragments 양식깨짐 수정

ks44team03/src/main/java/ks44team03/admin/controller/MainController.java, ks44team03/src/main/resources/templates/login/dormantRecoveryRegistration.html, ks44team03/src/main/resources/templates/login/findId.html, ks44team03/src/main/resources/templates/login/findPw.html, ks44team03/src/main/resources/templates/login/loginForm.html, ks44team03/src/main/resources/templates/login/loginRecordManagement.html, ks44team03/src/main/resources/templates/myPage/mypage.html
author : 문지혜
file : mypage.html
detail : mypage파일 css 깨지는 이유가 layout:decorate가 레이아웃의 mypage로 잡혀있으니 안되는거. 디폴트 레이아웃으로 바꿈
=> [ks44team03] mypage파일 layout:decorate 변경

ks44team03/src/main/resources/static/assets/css/all.css, ks44team03/src/main/resources/templates/myPage/mypage.html
author : 이국현
file : mypage.html, all.css
detail : mypage 상단부분 css 수정, all.css로 css 코드 분리중
=> [ks44team03] : mypage 상단부분 수정

ks44team03/src/main/java/ks44team03/admin/controller/CompanyInfoController.java, ks44team03/src/main/resources/templates/adminFragments/adminHeader.html, ks44team03/src/main/resources/templates/company/choiceCompany.html, ks44team03/src/main/resources/templates/company/companyRegister.html
author : 김덕현
file : choiceCompany.html, companyRegister.html
detail : 관리자페이지 - 관리등록 선택화면, 회사등록 화면 추가
=> [ks44team03] 관리자페이지 - 관리등록 선택화면, 회사등록 화면 추가

ks44team03/src/main/resources/static/assets/css/all.css, ks44team03/src/main/resources/templates/fragments/information_sidebar.html, ks44team03/src/main/resources/templates/myPage/applicationDetailSearch.html
author : 이국현
file : applicationDetailSearch.html
detail : all.css파일에 마지막 추가, 주문서상세내역 더하는중
​
=> [ks44team03] : 주문서상세내역

ks44team03/src/main/resources/static/assets/css/lee.css, ks44team03/src/main/resources/templates/myPage/member/mypageScreen.html
author : 이국현
detail : 마이페이지 하단부분 정리
=> [ks44team03] : 마이페이지 코드 정리

ks44team03/src/main/resources/templates/adminFragments/adminHeader.html, ks44team03/src/main/resources/templates/incoming/incomingNodata.html, ks44team03/src/main/resources/templates/incoming/incomingRegister.html
author : 한효송
file : incomingNodata.html, incomingRegister.html
detail : 버튼 글자만 눌러지던 것 수정, incomingRegister 경로 설정
=> [ks44team03] 노데이터 버튼 변경, 입고관리 연결

ks44team03/src/main/java/ks44team03/user/controller/MemberController.java, ks44team03/src/main/resources/templates/introduction/aboutDa.html, ks44team03/src/main/resources/templates/registration/userForm.html
author : 문지혜
file : 멤버컨트롤러
detail : 멤버컨트롤러 메소드명 변경
=> [ks44team03] 멤버컨트롤러 메소드명 변경

ks44team03/src/main/java/ks44team03/user/controller/CommunityController.java, ks44team03/src/main/resources/templates/adminFragments/adminHeader.html, ks44team03/src/main/resources/templates/community/postborde.html, ks44team03/src/main/resources/templates/community/reviewList.html, ks44team03/src/main/resources/templates/company/companyRegister.html, ks44team03/src/main/resources/templates/fragments/community_sidebar.html, ks44team03/src/main/resources/templates/fragments/header.html, ks44team03/src/main/resources/templates/layout/community_layout_sidebar.html
author : 김덕현
detail : 커뮤니티 화면 구현중임.
=> [ks44team03] 커뮤니티 화면 구현중

ks44team03/src/main/resources/static/assets/css/lee.css, ks44team03/src/main/resources/templates/myPage/applicationEdit.html
author : 이국현
detail : 배송신청서 수정 양식 구현중 container 크기 바꾸는법 생각중
​
=> [ks44team03] : 배송신청서 수정 양식 구현중

ks44team03/src/main/resources/templates/CustomerService/personalQuestionAnswerRegister.html, ks44team03/src/main/resources/templates/adminFragments/adminHeader.html
author : 주성민
detail : 1:1문의 답변 경로설정
=> [ks44team03] 1:1문의 답변

ks44team03/src/main/resources/static/assets/css/lee.css, ks44team03/src/main/resources/templates/myPage/applicationEdit.html
author : 이국현
detail : css에 body container크기 변경
=> [ks44team03] : applicationEdit수정중

ks44team03/src/main/java/ks44team03/common/controller/LoginController.java, ks44team03/src/main/resources/templates/adminFragments/adminConfig.html, ks44team03/src/main/resources/templates/adminFragments/adminHeader.html, ks44team03/src/main/resources/templates/adminLayout/adminDefault_layout.html, ks44team03/src/main/resources/templates/adminPage.html, ks44team03/src/main/resources/templates/login/loginRecordManagement.html, ks44team03/src/main/resources/templates/login/loginRecordManagement2.html
author: 문지혜
detail: 로그인이력페이지 생성 및 어드민디폴트템플릿 수정
=> [ksmart] 로그인이력페이지 생성

ks44team03/src/main/java/ks44team03/admin/controller/IncomingController.java, ks44team03/src/main/resources/templates/adminFragments/adminHeader.html, ks44team03/src/main/resources/templates/incoming/incomingNodata.html, ks44team03/src/main/resources/templates/incoming/incomingSearch.html
author : 한효송
file : insertSearch.html
detail : 입고관리현황 구현-연결 완료, 노데이터 입고관리 파일첨부버튼 type=file로 변경
=> [ks44team03] 입고관리현황

ks44team03/src/main/resources/templates/login/loginRecordManagement.html
author: 문지혜
detail: 회원 로그인관리 셀렉박스 수정 - 아직 작업중
=> [likey] 로그인관리 셀렉박스수정

ks44team03/src/main/java/ks44team03/admin/controller/CompanyInfoController.java, ks44team03/src/main/java/ks44team03/admin/service/CompanyInfoService.java, ks44team03/src/main/java/ks44team03/common/mapper/CommonMapper.java, ks44team03/src/main/resources/mapper/CommonMapper.xml, ks44team03/src/main/resources/mapper/CompanyMapper.xml, ks44team03/src/main/resources/static/adminPage/vendors/css/admin_page.css, ks44team03/src/main/resources/templates/company/companyList.html, ks44team03/src/main/resources/templates/company/companyRegister.html, ks44team03/src/main/resources/templates/company/department/departmentRegister.html, ks44team03/src/main/resources/templates/company/employee/employeeRegister.html, ks44team03/src/main/resources/templates/company/workplace/workPlaceRegister.html
author : 김덕현
detail : 회사목록 조회 오류 수정완료, 회사등록 기능 구현,
src/main/resources/mapper/CommonMapper.xml (공통)자동 코드증가 SQL문
추가, ks44team03.common.mapper패키지에 CommonMapper.java 인터페이스 추가
=> [ks44team03] - 회사목록 오류 수정완료 외 1

ks44team03/src/main/java/ks44team03/dto/UserInfo.java, ks44team03/src/main/java/ks44team03/user/controller/MypageController.java, ks44team03/src/main/java/ks44team03/user/mapper/MypageMapper.java, ks44team03/src/main/java/ks44team03/user/service/MypageService.java, ks44team03/src/main/resources/mapper/MypageMapper.xml, ks44team03/src/main/resources/templates/myPage/member/mypageScreen.html
author : 이국현
file : Mypage.html
detail : sql 작성중
=> [ks44team03] : Mypage 값 집어넣는중

ks44team03/pom.xml, ks44team03/src/main/java/ks44team03/dto/Login.java, ks44team03/src/main/java/ks44team03/user/controller/MemberController.java, ks44team03/src/main/java/ks44team03/user/mapper/MemberMapper.java, ks44team03/src/main/java/ks44team03/user/service/MemberService.java, ks44team03/src/main/resources/templates/login/loginForm.html, ks44team03/src/main/resources/templates/registration/userForm.html
author: 문지혜
detail: 유저-멤버컨트롤러수정
=> [ksmart] 유저-멤버컨트롤러수정

ks44team03/src/main/java/ks44team03/dto/Grade.java, ks44team03/src/main/java/ks44team03/dto/UserInfo.java, ks44team03/src/main/java/ks44team03/user/controller/MypageController.java, ks44team03/src/main/java/ks44team03/user/mapper/MypageMapper.java, ks44team03/src/main/java/ks44team03/user/service/MypageService.java, ks44team03/src/main/resources/application.properties, ks44team03/src/main/resources/log4jdbc.log4j2.properties, ks44team03/src/main/resources/logback-spring.xml, ks44team03/src/main/resources/mapper/MypageMapper.xml, ks44team03/src/main/resources/templates/myPage/member/mypageScreen.html
author : 이국현
detail : 맵퍼, 서비스 생성
=> [ks44team03] : 마이페이지 db연결작업

ks44team03/src/main/java/ks44team03/common/controller/CustomerNoticeController.java, ks44team03/src/main/java/ks44team03/common/mapper/CustomerNoticeMapper.java, ks44team03/src/main/java/ks44team03/common/service/CustomerNoticeService.java, ks44team03/src/main/resources/mapper/CustomerServiceMapper.xml, ks44team03/src/main/resources/templates/customerService/noticeSearch.html
=> [ks44team03] 공지사항 mvc

ks44team03/src/main/java/ks44team03/dto/Coupon.java, ks44team03/src/main/java/ks44team03/user/controller/MypageController.java, ks44team03/src/main/java/ks44team03/user/mapper/MypageMapper.java, ks44team03/src/main/java/ks44team03/user/service/MypageService.java, ks44team03/src/main/resources/mapper/MypageMapper.xml, ks44team03/src/main/resources/templates/myPage/member/mypageScreen.html
author : 이국현
file : MypageScreen.html
detail : 쿠폰 카운트 sql 설정
​
=> [ks44team03] : mypage 데이터 값 입력중

ks44team03/src/main/java/ks44team03/dto/Login.java, ks44team03/src/main/resources/templates/applicationForm/applicationFormRegister.html, ks44team03/src/main/resources/templates/applicationForm/friendsApplicationFormRegister.html
author : 문지혜
file : applicationFormRegister.html
friendsApplicationFormRegister.html
detail :대행신청서 양식 일부 수정
=> ﻿[ks44team03] 주문서양식수정

ks44team03/src/main/java/ks44team03/admin/controller/CompanyInfoController.java, ks44team03/src/main/java/ks44team03/admin/mapper/CompanyInfoMapper.java, ks44team03/src/main/java/ks44team03/admin/service/CompanyInfoService.java, ks44team03/src/main/java/ks44team03/dto/WorkPlace.java, ks44team03/src/main/resources/mapper/CommonMapper.xml, ks44team03/src/main/resources/mapper/CompanyMapper.xml, ks44team03/src/main/resources/templates/company/companyList.html, ks44team03/src/main/resources/templates/company/department/departmentList.html, ks44team03/src/main/resources/templates/company/employee/employeeList.html, ks44team03/src/main/resources/templates/company/workPlace/workPlaceList.html, ks44team03/src/main/resources/templates/company/workPlace/workPlaceRegister.html, ks44team03/src/main/resources/templates/orderList/goodsInfo.html
author : 김덕현
detail : 사업장 등록 기능 구현중 (쿼리문 오류 수정중)
=> [ks44team03] 사업장 등록 기능 구현중

ks44team03/pom.xml, ks44team03/src/main/java/ks44team03/dto/MyPageCount.java, ks44team03/src/main/java/ks44team03/dto/OrderInfo.java, ks44team03/src/main/java/ks44team03/user/controller/MypageController.java, ks44team03/src/main/java/ks44team03/user/mapper/MypageMapper.java, ks44team03/src/main/java/ks44team03/user/service/MypageService.java, ks44team03/src/main/resources/mapper/MypageMapper.xml, ks44team03/src/main/resources/templates/myPage/member/mypageScreen.html
author : 이국현
detail : 마이페이지 및 관련된 컨트롤러, 서비스, 맵퍼 작업중
=> [ks44team03] : 마이페이지 값 넣는중

ks44team03/src/main/java/ks44team03/admin/controller/CompanyInfoController.java, ks44team03/src/main/java/ks44team03/dto/WorkPlace.java, ks44team03/src/main/resources/mapper/CompanyMapper.xml, ks44team03/src/main/resources/templates/company/workPlace/workPlaceRegister.html
author : 김덕현
detail : 사업장 등록기능 구현중에 CompanyMapper.xml SQL오류 수정중
=> [ks44team03] - 사업장 등록기능 구현중

ks44team03/src/main/java/ks44team03/common/controller/CustomerNoticeController.java, ks44team03/src/main/java/ks44team03/common/mapper/CustomerNoticeMapper.java, ks44team03/src/main/java/ks44team03/common/service/CustomerNoticeService.java, ks44team03/src/main/resources/mapper/NoticeCenterMapper.xml, ks44team03/src/main/resources/templates/customerService/noticeSearchRead.html
=> [ks44team03] 공지사항 게시물 연결중

ks44team03/src/main/java/ks44team03/admin/controller/CompanyInfoController.java, ks44team03/src/main/java/ks44team03/dto/WorkPlace.java, ks44team03/src/main/resources/mapper/CompanyMapper.xml, ks44team03/src/main/resources/templates/company/workPlace/workPlaceRegister.html
author : 김덕현
detail : 사업장등록 기능 구현완료, ComapnyMapper.xml 사업장 insert 쿼리 오류 수정완료
=> [ks44team03] 사업장등록 기능 구현완료

ks44team03/src/main/java/ks44team03/dto/Forwarding.java, ks44team03/src/main/java/ks44team03/dto/Incoming.java
author : 한효송
file : Forwarding.java, Incoming.java
detail :
=> [ks44team03] 입출고 dto

ks44team03/src/main/java/ks44team03/admin/service/CompanyInfoService.java, ks44team03/src/main/java/ks44team03/common/controller/CustomerNoticeController.java, ks44team03/src/main/java/ks44team03/common/controller/CustomerScheduleController.java, ks44team03/src/main/java/ks44team03/common/mapper/CustomerNoticeMapper.java, ks44team03/src/main/java/ks44team03/common/mapper/CustomerScheduleMapper.java, ks44team03/src/main/java/ks44team03/common/service/CustomerNoticeService.java, ks44team03/src/main/java/ks44team03/common/service/CustomerScheduleService.java, ks44team03/src/main/java/ks44team03/dto/NoticeCenter.java, ks44team03/src/main/java/ks44team03/dto/ScheduleCenter.java, ks44team03/src/main/resources/mapper/NoticeCenterMapper.xml, ks44team03/src/main/resources/mapper/ScheduleCenterMapper.xml, ks44team03/src/main/resources/templates/customerService/deliveryScheduleSearch.html, ks44team03/src/main/resources/templates/customerService/deliveryScheduleSearchRead.html, ks44team03/src/main/resources/templates/customerService/noticeRead.html, ks44team03/src/main/resources/templates/customerService/noticeSearch.html
=> [ks44team03] 공지사항 게시글 내용,배송스케줄 게시글 내용 연결

ks44team03/src/main/java/ks44team03/common/controller/CustomerNoticeController.java, ks44team03/src/main/java/ks44team03/common/controller/CustomerQuestionController.java, ks44team03/src/main/java/ks44team03/common/controller/CustomerScheduleController.java, ks44team03/src/main/java/ks44team03/common/mapper/CustomerNoticeMapper.java, ks44team03/src/main/java/ks44team03/common/mapper/CustomerQuestionMapper.java, ks44team03/src/main/java/ks44team03/common/mapper/CustomerScheduleMapper.java, ks44team03/src/main/java/ks44team03/common/service/CustomerNoticeService.java, ks44team03/src/main/java/ks44team03/common/service/CustomerQuestionService.java, ks44team03/src/main/java/ks44team03/common/service/CustomerScheduleService.java, ks44team03/src/main/java/ks44team03/dto/QuestionCenter.java, ks44team03/src/main/resources/mapper/NoticeCenterMapper.xml, ks44team03/src/main/resources/mapper/QuestionCenterMapper.xml, ks44team03/src/main/resources/mapper/ScheduleCenterMapper.xml, ks44team03/src/main/resources/templates/customerService/personalQuestionAnswerRegister.html, ks44team03/src/main/resources/templates/customerService/personalQuestionRegister.html, ks44team03/src/main/resources/templates/customerService/personalQuestionSearchAdmin.html
=> [ks44team03] 관리자페이지 1:1문의 게시글 목록 연결

ks44team03/src/main/java/ks44team03/ServletInitializer.java, ks44team03/src/main/java/ks44team03/ks44team03Application.java, ks44team03/src/main/java/ks44team03/user/controller/myPageApiController.java, ks44team03/src/main/resources/templates/fragments/header.html, ks44team03/src/main/resources/templates/myPage/member/mypageScreen.html, ks44team03/src/main/resources/templates/myPage/myPageApi/allIn.html, ks44team03/src/main/resources/templates/myPage/myPageApi/arrived.html, ks44team03/src/main/resources/templates/myPage/myPageApi/buyingItem.html, ks44team03/src/main/resources/templates/myPage/myPageApi/err.html, ks44team03/src/main/resources/templates/myPage/myPageApi/orderType1.html, ks44team03/src/main/resources/templates/myPage/myPageApi/partialStock.html, ks44team03/src/main/resources/templates/myPage/myPageApi/tempApi.html
author : 이국현
detail : 마이페이지 작업중
​
=> [ks44team03] : mypage 작업중

ks44team03/src/main/java/ks44team03/admin/controller/CompanyInfoController.java, ks44team03/src/main/java/ks44team03/admin/mapper/CompanyInfoMapper.java, ks44team03/src/main/java/ks44team03/admin/service/CompanyInfoService.java, ks44team03/src/main/java/ks44team03/dto/Department.java, ks44team03/src/main/java/ks44team03/dto/Employee.java, ks44team03/src/main/resources/mapper/CompanyMapper.xml, ks44team03/src/main/resources/templates/company/department/departmentList.html, ks44team03/src/main/resources/templates/company/department/departmentRegister.html, ks44team03/src/main/resources/templates/company/employee/employeeList.html, ks44team03/src/main/resources/templates/company/employee/employeeRegister.html, ks44team03/src/main/resources/templates/orderList/orderList.html
author : 김덕현
detail : 회사, 사업장, 부서, 사원 목록조회 수정, 사업장, 부서 등록기능 구현
사원 등록기능 구현중
=> [ks44team03] 회사, 사업장, 부서, 사원 목록조회 수정, 사업장, 부서 등록기능 구현

ks44team03/src/main/java/ks44team03/admin/controller/CompanyInfoController.java, ks44team03/src/main/java/ks44team03/admin/mapper/CompanyInfoMapper.java, ks44team03/src/main/java/ks44team03/admin/service/CompanyInfoService.java, ks44team03/src/main/java/ks44team03/dto/Employee.java, ks44team03/src/main/java/ks44team03/dto/ManagementLevel.java, ks44team03/src/main/resources/mapper/CommonMapper.xml, ks44team03/src/main/resources/mapper/CompanyMapper.xml, ks44team03/src/main/resources/templates/company/companyRegister.html, ks44team03/src/main/resources/templates/company/employee/employeeList.html, ks44team03/src/main/resources/templates/company/employee/employeeRegister.html
author : 김덕현
detail : 부서, 사원 등록기능 구현완료, 공통 코드자동증가 sql 보안
=> [ks44team03] 부서, 사원 등록기능 구현완료

ks44team03/src/main/java/ks44team03/dto/MyPageCount.java, ks44team03/src/main/java/ks44team03/user/controller/MypageController.java, ks44team03/src/main/java/ks44team03/user/controller/myPageApiController.java, ks44team03/src/main/java/ks44team03/user/mapper/MypageMapper.java, ks44team03/src/main/java/ks44team03/user/service/MypageService.java, ks44team03/src/main/resources/mapper/CompanyMapper.xml, ks44team03/src/main/resources/mapper/MypageMapper.xml, ks44team03/src/main/resources/templates/myPage/member/mypageScreen.html, ks44team03/src/main/resources/templates/myPage/myPageApi/customsClosed.html, ks44team03/src/main/resources/templates/myPage/myPageApi/customsing.html, ks44team03/src/main/resources/templates/myPage/myPageApi/gsiOut.html, ks44team03/src/main/resources/templates/myPage/myPageApi/keepFeeCnt.html, ks44team03/src/main/resources/templates/myPage/myPageApi/localShipping.html, ks44team03/src/main/resources/templates/myPage/myPageApi/noOutNoPayCnt.html, ks44team03/src/main/resources/templates/myPage/myPageApi/noOutPaid.html, ks44team03/src/main/resources/templates/myPage/myPageApi/nodataApi.html, ks44team03/src/main/resources/templates/myPage/myPageApi/outNoPay.html, ks44team03/src/main/resources/templates/myPage/myPageApi/shipClosed.html, ks44team03/src/main/resources/templates/myPage/myPageApi/weightShipHold.html
author : 이국현
detail : mypage db 작업중
=> [ks44team03] : mypage작업중

ks44team03/src/main/java/ks44team03/common/controller/CustomerScheduleController.java, ks44team03/src/main/java/ks44team03/common/mapper/CustomerScheduleMapper.java, ks44team03/src/main/java/ks44team03/common/service/CustomerScheduleService.java, ks44team03/src/main/resources/mapper/ScheduleCenterMapper.xml
=> [ks44team03] 배송스케줄 등록 연결

ks44team03/src/main/java/ks44team03/admin/controller/CompanyInfoController.java, ks44team03/src/main/java/ks44team03/admin/mapper/CompanyInfoMapper.java, ks44team03/src/main/java/ks44team03/admin/service/CompanyInfoService.java, ks44team03/src/main/resources/mapper/CompanyMapper.xml, ks44team03/src/main/resources/static/adminPage/vendors/css/admin_page.css, ks44team03/src/main/resources/templates/company/companyList.html, ks44team03/src/main/resources/templates/company/department/departmentList.html, ks44team03/src/main/resources/templates/company/department/searchDepartmentList.html, ks44team03/src/main/resources/templates/company/employee/employeeList.html, ks44team03/src/main/resources/templates/company/employee/searchEmployeeList.html, ks44team03/src/main/resources/templates/company/searchCompanyList.html, ks44team03/src/main/resources/templates/company/workPlace/searchWorkPlaceList.html, ks44team03/src/main/resources/templates/company/workPlace/workPlaceList.html
author : 김덕현
detail : 회사, 사업장, 부서, 사원 목록 검색기능 구현 완료!
=> [ks44team03] - 회사, 사업장, 부서, 사원 목록 검색기능 구현

ks44team03/src/main/resources/templates/company/companyList.html, ks44team03/src/main/resources/templates/company/modifyCompany.html, ks44team03/src/main/resources/templates/company/workPlace/workPlaceList.html
author : 김덕현
detail : 회사정보수정 기능 구현중~
=> [ks44team03] 회사정보수정 기능 구현중

ks44team03/src/main/java/ks44team03/common/controller/CustomerScheduleController.java, ks44team03/src/main/java/ks44team03/common/service/CustomerScheduleService.java, ks44team03/src/main/resources/mapper/ScheduleCenterMapper.xml, ks44team03/src/main/resources/templates/customerService/schedule/deliveryScheduleModify.html
author : 주성민
detail : where 조건에 해당하는 값을 불러오지 못해서 input>display none 활용하여 숨긴 후 값을 맞춰 수정 가능하게 함
=> [ks44team03] 배송스케줄 수정하기 누르면 수정 완료

ks44team03/src/main/java/ks44team03/common/controller/CustomerScheduleController.java, ks44team03/src/main/java/ks44team03/common/mapper/CustomerScheduleMapper.java, ks44team03/src/main/java/ks44team03/common/service/CustomerScheduleService.java, ks44team03/src/main/resources/mapper/ScheduleCenterMapper.xml, ks44team03/src/main/resources/templates/customerService/schedule/deliveryScheduleDelete.html, ks44team03/src/main/resources/templates/customerService/schedule/deliveryScheduleSearchRead.html
=> [ks44team03] 배송스케줄 삭제 경로만 설정

ks44team03/src/main/java/ks44team03/user/controller/MypageController.java, ks44team03/src/main/java/ks44team03/user/controller/myPageApiController.java, ks44team03/src/main/java/ks44team03/user/mapper/MypageMapper.java, ks44team03/src/main/java/ks44team03/user/service/MypageService.java, ks44team03/src/main/resources/mapper/MypageMapper.xml, ks44team03/src/main/resources/templates/myPage/member/mypageScreen.html
author : 이국현
detail : mypage 카운트 작업
=> [ks44team03] : mypage 카운트 작업

ks44team03/src/main/java/ks44team03/common/controller/CustomerQuestionController.java, ks44team03/src/main/java/ks44team03/common/mapper/CustomerQuestionMapper.java, ks44team03/src/main/java/ks44team03/common/service/CustomerQuestionService.java, ks44team03/src/main/resources/mapper/NoticeCenterMapper.xml, ks44team03/src/main/resources/mapper/QuestionCenterMapper.xml, ks44team03/src/main/resources/static/assets/css/temporarily.css, ks44team03/src/main/resources/templates/customerService/notice/noticeRead.html, ks44team03/src/main/resources/templates/customerService/notice/noticeSearch.html, ks44team03/src/main/resources/templates/customerService/question/MyQuestionRead.html, ks44team03/src/main/resources/templates/customerService/question/myQuestionList.html, ks44team03/src/main/resources/templates/customerService/question/personalQuestionRegister.html, ks44team03/src/main/resources/templates/customerService/question/personalQuestionSearchAdmin.html, ks44team03/src/main/resources/templates/customerService/schedule/deliveryScheduleRegister.html, ks44team03/src/main/resources/templates/customerService/schedule/deliveryScheduleSearch.html, ks44team03/src/main/resources/templates/customerService/schedule/deliveryScheduleSearchRead.html, ks44team03/src/main/resources/templates/fragments/header.html
=> [ks44team03] 1:1문의 셀렉트 박스 db 적용

ks44team03/src/main/java/ks44team03/admin/controller/CompanyInfoController.java, ks44team03/src/main/java/ks44team03/admin/mapper/CompanyInfoMapper.java, ks44team03/src/main/java/ks44team03/admin/service/CompanyInfoService.java, ks44team03/src/main/resources/mapper/CompanyMapper.xml, ks44team03/src/main/resources/templates/company/companyRegister.html, ks44team03/src/main/resources/templates/company/department/departmentList.html, ks44team03/src/main/resources/templates/company/department/departmentRegister.html, ks44team03/src/main/resources/templates/company/department/modifyDepartment.html, ks44team03/src/main/resources/templates/company/employee/employeeList.html, ks44team03/src/main/resources/templates/company/employee/modifyEmployee.html, ks44team03/src/main/resources/templates/company/employee/removeEmployee.html, ks44team03/src/main/resources/templates/company/workPlace/modifyWorkPlace.html, ks44team03/src/main/resources/templates/company/workPlace/workPlaceList.html
author : 김덕현
detail : 회사등록 중복유효성검사 기능구현, 사업장, 부서, 사원 수정기능 구현
employee.html jquery 연습중
=> [ks44team03] 회사 관련 특정정보 수정기능 구현

ks44team03/src/main/java/ks44team03/common/controller/CustomerQuestionController.java, ks44team03/src/main/java/ks44team03/common/mapper/CustomerQuestionMapper.java, ks44team03/src/main/java/ks44team03/common/service/CustomerQuestionService.java, ks44team03/src/main/java/ks44team03/common/service/CustomerScheduleService.java, ks44team03/src/main/resources/mapper/QuestionCenterMapper.xml, ks44team03/src/main/resources/templates/customerService/question/MyQuestionRead.html, ks44team03/src/main/resources/templates/customerService/question/myQuestionModify.html, ks44team03/src/main/resources/templates/customerService/question/personalQuestionAnswerRegister.html, ks44team03/src/main/resources/templates/customerService/question/personalQuestionSearchAdmin.html
=> [ks44team03] 1:1문의 상태 변경중

ks44team03/src/main/java/ks44team03/dto/ShipOrderApi.java, ks44team03/src/main/java/ks44team03/user/controller/MypageController.java, ks44team03/src/main/java/ks44team03/user/controller/myPageApiController.java, ks44team03/src/main/java/ks44team03/user/mapper/MypageMapper.java, ks44team03/src/main/java/ks44team03/user/service/MypageService.java, ks44team03/src/main/resources/mapper/MypageMapper.xml, ks44team03/src/main/resources/templates/myPage/member/mypageScreen.html, ks44team03/src/main/resources/templates/myPage/myPageApi/shipOrderApi.html
author : 이국현
detail : 마이페이지 ajax작업중
=> [ks44team03] : mypage 아래부분 작업

ks44team03/src/main/java/ks44team03/common/controller/CustomerNoticeController.java, ks44team03/src/main/java/ks44team03/common/controller/CustomerQuestionController.java, ks44team03/src/main/java/ks44team03/common/mapper/CustomerNoticeMapper.java, ks44team03/src/main/java/ks44team03/common/mapper/CustomerQuestionMapper.java, ks44team03/src/main/java/ks44team03/common/service/CustomerNoticeService.java, ks44team03/src/main/java/ks44team03/common/service/CustomerQuestionService.java, ks44team03/src/main/java/ks44team03/dto/QuestionCenter.java, ks44team03/src/main/resources/mapper/NoticeCenterMapper.xml, ks44team03/src/main/resources/mapper/QuestionCenterMapper.xml, ks44team03/src/main/resources/templates/customerService/notice/noticeModify.html, ks44team03/src/main/resources/templates/customerService/notice/noticeRead.html, ks44team03/src/main/resources/templates/customerService/notice/noticeSearch.html, ks44team03/src/main/resources/templates/customerService/question/personalQuestionAnswerRegister.html, ks44team03/src/main/resources/templates/customerService/schedule/deliveryScheduleModify.html
=> [ks44team03] 1:1문의 답변 등록

ks44team03/src/main/java/ks44team03/common/controller/CustomerQuestionController.java, ks44team03/src/main/java/ks44team03/common/service/CustomerQuestionService.java, ks44team03/src/main/resources/mapper/QuestionCenterMapper.xml, ks44team03/src/main/resources/templates/customerService/question/personalQuestionAnswerRegister.html, ks44team03/src/main/resources/templates/customerService/question/personalQuestionSearchAdmin.html
=> [ks44team03] 관리자 페이지에서 1:1문의 클릭 시 처리중으로 바뀜

ks44team03/src/main/resources/mapper/CommonMapper.xml, ks44team03/src/main/resources/mapper/QuestionCenterMapper.xml, ks44team03/src/main/resources/templates/customerService/question/personalQuestionSearchAdmin.html
=> [ks44team03] 관리자 페이지 1:1문의 select option 설정중

ks44team03/src/main/java/ks44team03/admin/controller/AdminOrderController.java, ks44team03/src/main/java/ks44team03/admin/mapper/OrderMapper.java, ks44team03/src/main/java/ks44team03/admin/service/OrderService.java, ks44team03/src/main/java/ks44team03/dto/Community.java, ks44team03/src/main/java/ks44team03/dto/DeliveryCurrentState.java, ks44team03/src/main/java/ks44team03/dto/GoodsInfo.java, ks44team03/src/main/java/ks44team03/user/controller/CommunityController.java, ks44team03/src/main/java/ks44team03/user/mapper/CommunityMapper.java, ks44team03/src/main/java/ks44team03/user/service/CommunityService.java, ks44team03/src/main/resources/mapper/AdminOrderListMapper.xml, ks44team03/src/main/resources/static/adminPage/vendors/css/admin_page.css, ks44team03/src/main/resources/templates/adminFragments/adminHeader.html, ks44team03/src/main/resources/templates/community/ReviewRegister.html, ks44team03/src/main/resources/templates/community/reviewInfo.html, ks44team03/src/main/resources/templates/company/employee/employeeList.html, ks44team03/src/main/resources/templates/orderList/adminOrderList.html, ks44team03/src/main/resources/templates/orderList/adminTempOrderList.html, ks44team03/src/main/resources/templates/orderList/delivery/deliveryOrderList.html
author : 김덕현
detail : 관리자페이지 주문서 목록 구현, 배송대행 신청완료 주문서목록 구현중
=> [ks44team03] 관리자 페이지 주문서목록 구현

ks44team03/src/main/resources/mapper/Incoming.xml
author : 한효송
file : incoming.xml
detail : ​오류난 거 주석처리 ㅎㅎ ㅈㅅㅈㅅ;;
=> [ks44team03]

ks44team03/src/main/java/ks44team03/admin/controller/AdminOrderController.java, ks44team03/src/main/java/ks44team03/admin/mapper/OrderMapper.java, ks44team03/src/main/java/ks44team03/admin/service/OrderService.java, ks44team03/src/main/java/ks44team03/dto/GoodsInfo.java, ks44team03/src/main/java/ks44team03/dto/IncomingInfo.java, ks44team03/src/main/java/ks44team03/dto/OrderState.java, ks44team03/src/main/resources/mapper/AdminOrderListMapper.xml, ks44team03/src/main/resources/static/adminPage/css/vertical-layout-light/style.css, ks44team03/src/main/resources/static/adminPage/vendors/css/admin_page.css, ks44team03/src/main/resources/templates/adminFragments/adminHeader.html, ks44team03/src/main/resources/templates/orderList/buyProgress/buyProgressOrderList.html, ks44team03/src/main/resources/templates/orderList/forwarding/completedForwardingList.html, ks44team03/src/main/resources/templates/orderList/forwarding/holdForwardingList.html, ks44team03/src/main/resources/templates/orderList/forwarding/waitingForwardingList.html
author : 김덕현
detail : admin페이지 주문서 목록메뉴 구현
=> [ks44team03] admin페이지 주문서 목록메뉴 구현

ks44team03/src/main/resources/templates/adminFragments/adminHeader.html, ks44team03/src/main/resources/templates/adminPage.html
author : 김덕현
detail : admin페이지 메뉴 정리
=> [ks44team03] admin페이지 메뉴 정리

ks44team03/src/main/java/ks44team03/common/controller/CustomerNoticeController.java, ks44team03/src/main/java/ks44team03/common/controller/CustomerQuestionController.java, ks44team03/src/main/java/ks44team03/common/mapper/CustomerNoticeMapper.java, ks44team03/src/main/java/ks44team03/common/mapper/CustomerQuestionMapper.java, ks44team03/src/main/java/ks44team03/common/service/CustomerNoticeService.java, ks44team03/src/main/java/ks44team03/common/service/CustomerQuestionService.java, ks44team03/src/main/resources/mapper/NoticeCenterMapper.xml, ks44team03/src/main/resources/mapper/QuestionCenterMapper.xml, ks44team03/src/main/resources/templates/customerService/notice/.html, ks44team03/src/main/resources/templates/customerService/notice/noticeList.html, ks44team03/src/main/resources/templates/customerService/notice/noticeModify.html, ks44team03/src/main/resources/templates/customerService/notice/noticeRead.html, ks44team03/src/main/resources/templates/customerService/notice/noticeSearch.html, ks44team03/src/main/resources/templates/customerService/question/MyQuestionRead.html, ks44team03/src/main/resources/templates/customerService/question/deleteQuestion.html, ks44team03/src/main/resources/templates/customerService/question/personalQuestionAnswerRegister.html, ks44team03/src/main/resources/templates/customerService/question/personalQuestionSearchAdmin.html, ks44team03/src/main/resources/templates/customerService/question/searchQuestion.html, ks44team03/src/main/resources/templates/customerService/testPage.html, ks44team03/src/main/resources/templates/fragments/footer.html, ks44team03/src/main/resources/templates/fragments/header.html
=> [ks44team03] 관리자 페이지 1:1문의 검색기능 수정중

ks44team03/src/main/java/ks44team03/common/controller/CustomerNoticeController.java, ks44team03/src/main/java/ks44team03/common/controller/CustomerQuestionController.java, ks44team03/src/main/java/ks44team03/common/service/CustomerScheduleService.java, ks44team03/src/main/resources/mapper/QuestionCenterMapper.xml, ks44team03/src/main/resources/mapper/ScheduleCenterMapper.xml, ks44team03/src/main/resources/templates/customerService/question/personalQuestionSearchAdmin.html, ks44team03/src/main/resources/templates/customerService/question/searchQuestion.html
=> [ks44team03] 관리자페이지 1:1문의 검색 연결 , 스케줄 db명 schedule_center로변경

ks44team03/src/main/java/ks44team03/common/controller/CustomerScheduleController.java, ks44team03/src/main/java/ks44team03/dto/NoticeCenter.java, ks44team03/src/main/resources/mapper/NoticeCenterMapper.xml, ks44team03/src/main/resources/mapper/QuestionCenterMapper.xml, ks44team03/src/main/resources/templates/customerService/faq/faqList/faq1.html, ks44team03/src/main/resources/templates/customerService/faq/faqSearch.html, ks44team03/src/main/resources/templates/customerService/notice/noticeList.html, ks44team03/src/main/resources/templates/customerService/notice/noticeRegister.html, ks44team03/src/main/resources/templates/customerService/question/personalQuestionSearchAdmin.html, ks44team03/src/main/resources/templates/customerService/schedule/deliveryScheduleRegister.html
=> [ks44team03] 자주하는 질문 jquery 연결중

ks44team03/src/main/java/ks44team03/dto/Community.java, ks44team03/src/main/java/ks44team03/user/controller/CommunityController.java, ks44team03/src/main/java/ks44team03/user/mapper/CommunityMapper.java, ks44team03/src/main/java/ks44team03/user/service/CommunityService.java, ks44team03/src/main/resources/mapper/CommunityMapper.xml, ks44team03/src/main/resources/templates/community/reviewInfo.html, ks44team03/src/main/resources/templates/community/reviewList.html, ks44team03/src/main/resources/templates/community/reviewRegister.html
author : 김덕현
detail : 커뮤니티 게시판 이용후기 리스트, 등록 기능 구현
=> [ks44team03] 커뮤니티 게시판 이용후기 구현

ks44team03/src/main/java/ks44team03/admin/controller/IncomingController.java, ks44team03/src/main/java/ks44team03/admin/mapper/IncomingMapper.java, ks44team03/src/main/java/ks44team03/admin/service/IncomingService.java, ks44team03/src/main/java/ks44team03/dto/Criteria.java, ks44team03/src/main/java/ks44team03/dto/PageMakeDTO.java, ks44team03/src/main/resources/mapper/Incoming.xml, ks44team03/src/main/resources/templates/adminFragments/adminHeader.html, ks44team03/src/main/resources/templates/incoming/deliveryComplete.html, ks44team03/src/main/resources/templates/incoming/inTransit.html, ks44team03/src/main/resources/templates/incoming/incomingList.html, ks44team03/src/main/resources/templates/incoming/storageCharge.html
author : 이국현
detail : 관리자페이지 목록 추가
=> [ks44team03] :관리자페이지 목록 추가

ks44team03/src/main/java/ks44team03/admin/controller/IncomingController.java, ks44team03/src/main/java/ks44team03/admin/mapper/IncomingMapper.java, ks44team03/src/main/java/ks44team03/admin/service/IncomingService.java, ks44team03/src/main/resources/mapper/Incoming.xml
author : 이국현
file : incoming.html
detail : 페이징 작업 처리중
=> [ks44team03] : 페이징 작업 처리중

ks44team03/src/main/java/ks44team03/common/controller/CustomerFaqController.java, ks44team03/src/main/java/ks44team03/common/mapper/CustomerFaqMapper.java, ks44team03/src/main/java/ks44team03/common/service/CustomerFaqService.java, ks44team03/src/main/java/ks44team03/dto/FaqCenter.java, ks44team03/src/main/resources/mapper/FaqCenterMapper.xml, ks44team03/src/main/resources/static/assets/css/temporarily.css, ks44team03/src/main/resources/templates/customerService/faq/faqRegister.html, ks44team03/src/main/resources/templates/customerService/faq/faqSearch.html
=> [ks44team03] 자주하는 질문 jquery,db 연결

ks44team03/src/main/java/ks44team03/common/controller/CustomerQuestionController.java, ks44team03/src/main/java/ks44team03/common/service/CustomerQuestionService.java, ks44team03/src/main/resources/mapper/QuestionCenterMapper.xml, ks44team03/src/main/resources/templates/customerService/faq/faqSearch.html, ks44team03/src/main/resources/templates/customerService/question/myQuestionList.html, ks44team03/src/main/resources/templates/customerService/question/myQuestionRead.html, ks44team03/src/main/resources/templates/customerService/question/personalQuestionAnswerRegister.html, ks44team03/src/main/resources/templates/customerService/question/personalQuestionRegister.html, ks44team03/src/main/resources/templates/customerService/schedule/deliveryScheduleRegister.html
=> [ks44team03] 1:1문의 수정

ks44team03/src/main/java/ks44team03/admin/controller/IncomingController.java, ks44team03/src/main/java/ks44team03/admin/mapper/IncomingMapper.java, ks44team03/src/main/java/ks44team03/admin/service/IncomingService.java, ks44team03/src/main/resources/mapper/Incoming.xml, ks44team03/src/main/resources/static/adminPage/vendors/css/admin_page.css, ks44team03/src/main/resources/templates/incoming/incomingGoodsList.html, ks44team03/src/main/resources/templates/incoming/incomingList.html
author : 이국현
file : adminpage.html
detail : 모달창 띄우고 등록하는거 작업중
​
=> [ks44team03] : 모달창 띄우기 성공

ks44team03/src/main/resources/templates/customerService/notice/noticeModify.html, ks44team03/src/main/resources/templates/customerService/notice/noticeRegister.html, ks44team03/src/main/resources/templates/customerService/question/myQuestionModify.html, ks44team03/src/main/resources/templates/customerService/question/myQuestionRead.html, ks44team03/src/main/resources/templates/customerService/question/personalQuestionAnswerRegister.html, ks44team03/src/main/resources/templates/customerService/question/personalQuestionRegister.html, ks44team03/src/main/resources/templates/customerService/schedule/deliveryScheduleModify.html, ks44team03/src/main/resources/templates/customerService/schedule/deliveryScheduleRegister.html
=> [ks44team03] 고객센터 유효성검사

ks44team03/src/main/java/ks44team03/admin/controller/IncomingController.java, ks44team03/src/main/java/ks44team03/admin/mapper/IncomingMapper.java, ks44team03/src/main/java/ks44team03/admin/service/IncomingService.java, ks44team03/src/main/resources/mapper/Incoming.xml, ks44team03/src/main/resources/templates/incoming/incomingRegister.html
author : 한효송
file : incomingRegister.html
detail : ​입고등록 db랑 연결 중
=> [ks44team03] 입고등록 db와 연결 중

ks44team03/src/main/java/ks44team03/common/controller/CouponController.java, ks44team03/src/main/java/ks44team03/common/mapper/CouponMapper.java, ks44team03/src/main/java/ks44team03/common/service/CouponSerive.java, ks44team03/src/main/resources/mapper/CouponMapper.xml, ks44team03/src/main/resources/templates/adminFragments/adminHeader.html, ks44team03/src/main/resources/templates/couponManagementAdmin/couponAdmin.html, ks44team03/src/main/resources/templates/customerService/faq/faqSearch.html, ks44team03/src/main/resources/templates/customerService/schedule/deliveryScheduleModify.html
=> [ks44team03] 쿠폰 맵퍼xml 수정중

ks44team03/src/main/java/ks44team03/common/controller/CouponController.java, ks44team03/src/main/java/ks44team03/common/mapper/CouponMapper.java, ks44team03/src/main/java/ks44team03/common/service/CouponSerive.java, ks44team03/src/main/java/ks44team03/dto/CouponList.java, ks44team03/src/main/resources/mapper/CouponMapper.xml, ks44team03/src/main/resources/static/assets/css/temporarily.css, ks44team03/src/main/resources/templates/adminFragments/adminHeader.html, ks44team03/src/main/resources/templates/couponManagementAdmin/couponAdmin.html
=> [ks44team03] 관리자 페이지 쿠폰 리스트, 등록 db 연결

ks44team03/src/main/java/ks44team03/user/controller/CommunityController.java, ks44team03/src/main/java/ks44team03/user/mapper/CommunityMapper.java, ks44team03/src/main/java/ks44team03/user/service/CommunityService.java, ks44team03/src/main/resources/mapper/CommunityMapper.xml, ks44team03/src/main/resources/templates/community/modifyReview.html, ks44team03/src/main/resources/templates/community/reviewInfo.html, ks44team03/src/main/resources/templates/community/reviewRegister.html
author : 김덕현
detail : 이용후기 수정화면 구현중
=> [ks44team] 이용후기 수정화면 구현중

ks44team03/bin/src/main/resources/mapper/CompanyMapper.xml, ks44team03/src/main/java/ks44team03/admin/controller/IncomingController.java, ks44team03/src/main/java/ks44team03/admin/mapper/IncomingMapper.java, ks44team03/src/main/java/ks44team03/admin/service/IncomingService.java, ks44team03/src/main/java/ks44team03/user/controller/MypageController.java, ks44team03/src/main/java/ks44team03/user/mapper/MypageMapper.java, ks44team03/src/main/java/ks44team03/user/service/MypageService.java, ks44team03/src/main/resources/application.properties, ks44team03/src/main/resources/mapper/Incoming.xml, ks44team03/src/main/resources/mapper/MypageMapper.xml, ks44team03/src/main/resources/templates/incoming/incomingGoodsList.html, ks44team03/src/main/resources/templates/incoming/incomingList.html, ks44team03/src/main/resources/templates/myPage/myPageApi/shipOrderApi.html
author : 이국현
detail : 상품 임시저장 화면 수정중
​
=> [ks44team03] : 상품 임시저장 화면 수정중

ks44team03/src/main/java/ks44team03/user/controller/CommunityController.java, ks44team03/src/main/java/ks44team03/user/service/CommunityService.java, ks44team03/src/main/resources/mapper/CommunityMapper.xml, ks44team03/src/main/resources/templates/community/modifyReview.html, ks44team03/src/main/resources/templates/fragments/header.html
author : 김덕현
detail : 이용후기 게시판 글 수정기능 구현완료
=> [ks44team03] 이용후기 게시판 글 수정기능 구현완료

ks44team03/src/main/java/ks44team03/common/controller/CouponController.java, ks44team03/src/main/java/ks44team03/common/mapper/CouponMapper.java, ks44team03/src/main/java/ks44team03/common/service/CouponSerive.java, ks44team03/src/main/java/ks44team03/dto/Coupon.java, ks44team03/src/main/java/ks44team03/dto/CouponList.java, ks44team03/src/main/resources/mapper/CouponMapper.xml, ks44team03/src/main/resources/static/assets/css/temporarily.css, ks44team03/src/main/resources/templates/adminFragments/adminHeader.html, ks44team03/src/main/resources/templates/couponManagementAdmin/couponUserList.html, ks44team03/src/main/resources/templates/fragments/header.html
=> [ks44team03] 쿠폰보유현황 수정중

ks44team03/src/main/java/ks44team03/user/controller/MypageController.java, ks44team03/src/main/java/ks44team03/user/mapper/MypageMapper.java, ks44team03/src/main/java/ks44team03/user/service/MypageService.java, ks44team03/src/main/resources/mapper/MypageMapper.xml, ks44team03/src/main/resources/mapper/OderMapper.xml, ks44team03/src/main/resources/static/assets/css/temporarily.css, ks44team03/src/main/resources/templates/main.html, ks44team03/src/main/resources/templates/myPage/applicationEdit.html
author : 이국현
file : main.html
detail :  처음 뜨는 화면 수정
=> [ks44team03] : 처음 뜨는 화면 수정

ks44team03/src/main/java/ks44team03/admin/service/CompanyInfoService.java, ks44team03/src/main/java/ks44team03/dto/UserInfo.java, ks44team03/src/main/java/ks44team03/user/controller/MemberController.java, ks44team03/src/main/java/ks44team03/user/mapper/MemberMapper.java, ks44team03/src/main/java/ks44team03/user/service/MemberService.java, ks44team03/src/main/resources/mapper/SignupMapper.xml, ks44team03/src/main/resources/templates/fragments/config.html, ks44team03/src/main/resources/templates/fragments/header.html, ks44team03/src/main/resources/templates/login/loginForm.html, ks44team03/src/main/resources/templates/registration/userForm.html, ks44team03/src/main/webapp/top_logo.css
author : 문지혜
file : 로그인폼, 멤버컨트롤러
detail : 로그인작업중
=> ﻿[ks44team03]로그인 작업중

ks44team03/src/main/resources/templates/myPage/applicationEdit.html
author : 이국현
detail : applicationEdit 수정중
=> [ks44team03] : applicationEdit 수정중

ks44team03/src/main/java/ks44team03/user/controller/MemberController.java, ks44team03/src/main/resources/templates/fragments/header.html, ks44team03/src/main/resources/templates/login/loginForm.html
=> ﻿[ks44team03] 로그인

ks44team03/src/main/java/ks44team03/common/controller/CouponController.java, ks44team03/src/main/java/ks44team03/common/controller/CustomerNoticeController.java, ks44team03/src/main/java/ks44team03/common/controller/CustomerQuestionController.java, ks44team03/src/main/java/ks44team03/common/mapper/CouponMapper.java, ks44team03/src/main/java/ks44team03/common/mapper/CustomerQuestionMapper.java, ks44team03/src/main/java/ks44team03/common/service/CouponSerive.java, ks44team03/src/main/java/ks44team03/common/service/CustomerQuestionService.java, ks44team03/src/main/java/ks44team03/dto/Coupon.java, ks44team03/src/main/java/ks44team03/dto/QuestionCenter.java, ks44team03/src/main/resources/mapper/CouponMapper.xml, ks44team03/src/main/resources/mapper/QuestionCenterMapper.xml, ks44team03/src/main/resources/templates/couponManagementAdmin/couponAdmin.html, ks44team03/src/main/resources/templates/couponManagementAdmin/couponUserList.html, ks44team03/src/main/resources/templates/couponManagementAdmin/searchCoupon.html, ks44team03/src/main/resources/templates/customerService/question/personalQuestionAnswerRegister.html, ks44team03/src/main/resources/templates/customerService/question/personalQuestionSearchAdmin.html, ks44team03/src/main/resources/templates/customerService/testPage.html
=> [ks44team03] 쿠폰 조건 검색 수정중

ks44team03/src/main/resources/templates/myPage/applicationEdit.html
=> [ks44team03] : 임시저장 수정

ks44team03/pom.xml, ks44team03/src/main/resources/application.properties, ks44team03/src/main/resources/templates/myPage/applicationEdit.html
author : 이국현
detail : 서버포트 변경(8088)-application.properties, 배포패키지파일(jar변경)-pom.xml
=> [ks44team03] - jenkins 배포환경 셋팅

ks44team03/src/main/java/ks44team03/common/controller/CouponController.java, ks44team03/src/main/java/ks44team03/common/controller/CustomerQuestionController.java, ks44team03/src/main/resources/templates/couponManagementAdmin/couponUserList.html, ks44team03/src/main/resources/templates/couponManagementAdmin/searchCoupon.html
=> [ks44team03] 쿠폰 날짜 조건으로 조회

ks44team03/src/main/resources/templates/registration/userForm.html
=> ﻿[ks44team03] 경로수정

ks44team03/src/main/java/ks44team03/admin/controller/IncomingController.java, ks44team03/src/main/java/ks44team03/admin/mapper/IncomingMapper.java, ks44team03/src/main/java/ks44team03/admin/service/IncomingService.java, ks44team03/src/main/resources/mapper/Incoming.xml, ks44team03/src/main/resources/templates/community/reviewInfo.html, ks44team03/src/main/resources/templates/incoming/incomingRegister.html
=> [ks44team03] 오류입고 db연결

ks44team03/bin/src/main/resources/static/assets/css/lee.css, ks44team03/src/main/java/ks44team03/dto/OrderInfo.java, ks44team03/src/main/java/ks44team03/user/controller/myPageApiController.java, ks44team03/src/main/resources/templates/layout/default_layout.html, ks44team03/src/main/resources/templates/myPage/applicationEdit.html, ks44team03/src/main/resources/templates/myPage/myPageApi/jusoPopup.html
author : 이국현
detail : 주소api 사용중
​
=> [ks44team03] : 주소api 사용중

ks44team03/src/main/java/ks44team03/admin/controller/IncomingController.java, ks44team03/src/main/java/ks44team03/admin/mapper/IncomingMapper.java, ks44team03/src/main/java/ks44team03/admin/service/IncomingService.java, ks44team03/src/main/resources/mapper/Incoming.xml, ks44team03/src/main/resources/templates/adminFragments/adminHeader.html, ks44team03/src/main/resources/templates/incoming/goodsIncomingList.html, ks44team03/src/main/resources/templates/incoming/incomingRegister.html
=> [ks44team03] 입고등록 연결, 입고완료 상품목록 리스트 추가

ks44team03/src/main/resources/templates/incoming/incomingRegister.html
author : 한효송
file : incomingRegister.html
detail :
=> [ks44team03] incomingRegister td수정

ks44team03/src/main/java/ks44team03/common/controller/CustomerFaqController.java, ks44team03/src/main/java/ks44team03/common/controller/CustomerNoticeController.java, ks44team03/src/main/java/ks44team03/common/controller/CustomerQuestionController.java, ks44team03/src/main/java/ks44team03/common/controller/CustomerScheduleController.java, ks44team03/src/main/java/ks44team03/common/mapper/CustomerQuestionMapper.java, ks44team03/src/main/java/ks44team03/common/service/CustomerQuestionService.java, ks44team03/src/main/resources/mapper/QuestionCenterMapper.xml, ks44team03/src/main/resources/templates/customerService/question/myQuestionRead.html
=> [ks44team03] 내문의내역페이지에서 글 클릭 후 삭제 ajax 하는중

ks44team03/src/main/java/ks44team03/dto/GoodsInfo.java, ks44team03/src/main/java/ks44team03/user/controller/myPageApiController.java, ks44team03/src/main/resources/mapper/MypageMapper.xml, ks44team03/src/main/resources/templates/myPage/applicationEdit.html, ks44team03/src/main/resources/templates/myPage/myPageApi/jusoPopup.html
author : 이국현
file : 000.html
detail : 임시저장글 수정화면 수정중
=> [ks44team03] : 임시저장글 수정화면

ks44team03/src/main/resources/mapper/QuestionCenterMapper.xml, ks44team03/src/main/resources/templates/couponManagementAdmin/couponUserList.html
=> [ks44team03] 쿠폰 회원 보유 리스트 날짜 조건 jquery 완료

ks44team03/src/main/java/ks44team03/common/controller/CustomerQuestionController.java, ks44team03/src/main/java/ks44team03/common/service/CustomerQuestionService.java, ks44team03/src/main/resources/mapper/QuestionCenterMapper.xml, ks44team03/src/main/resources/templates/customerService/question/myQuestionRead.html
=> [ks44team03] 내문의내역 삭제 ajax 처리

ks44team03/src/main/java/ks44team03/admin/controller/MainController.java, ks44team03/src/main/java/ks44team03/dto/Coupon.java, ks44team03/src/main/java/ks44team03/dto/GoodsInfo.java, ks44team03/src/main/java/ks44team03/user/controller/MypageController.java, ks44team03/src/main/java/ks44team03/user/mapper/MypageMapper.java, ks44team03/src/main/java/ks44team03/user/service/MypageService.java, ks44team03/src/main/resources/mapper/MypageMapper.xml, ks44team03/src/main/resources/templates/myPage/applicationEdit.html
author : 이국현
detail : 쿠폰정보 가져오기 작업
​
=> [ks44team03] : 쿠폰정보 가져오기 작업

ks44team03/src/main/java/ks44team03/common/controller/CouponController.java, ks44team03/src/main/java/ks44team03/common/mapper/CouponMapper.java, ks44team03/src/main/java/ks44team03/common/service/CouponSerive.java, ks44team03/src/main/resources/mapper/CouponMapper.xml, ks44team03/src/main/resources/templates/couponManagementAdmin/couponAdmin.html, ks44team03/src/main/resources/templates/couponManagementAdmin/couponUserList.html, ks44team03/src/main/resources/templates/customerService/question/personalQuestionRegister.html
=> [ks44team03] 쿠폰 삭제 text 수정중

ks44team03/src/main/java/ks44team03/admin/controller/IncomingController.java, ks44team03/src/main/java/ks44team03/user/controller/MemberController.java, ks44team03/src/main/java/ks44team03/user/mapper/MemberMapper.java, ks44team03/src/main/java/ks44team03/user/service/MemberService.java, ks44team03/src/main/resources/mapper/SignupMapper.xml, ks44team03/src/main/resources/templates/login/findIdPw.html
author : 문지혜
detail : 비밀번호찾기 작업중
=> [ks44team03] 비밀번호찾기 작업중

ks44team03/src/main/resources/templates/couponManagementAdmin/couponAdmin.html
=> [ks44team03] 쿠폰 삭제 수정 완료

ks44team03/src/main/resources/templates/login/loginForm.html
author : 문지혜
detail : 로그인 제이쿼리 수정
=> ﻿[ks44team03] 로그인 제이쿼리 수정

ks44team03/src/main/java/ks44team03/user/controller/IntroductionController.java, ks44team03/src/main/java/ks44team03/user/controller/UserOrderController.java, ks44team03/src/main/resources/static/assets/css/introduction.css, ks44team03/src/main/resources/templates/fragments/header.html, ks44team03/src/main/resources/templates/introduction/aboutDa.html, ks44team03/src/main/resources/templates/introduction/aboutFriendsPa.html, ks44team03/src/main/resources/templates/introduction/aboutPa.html
author : 문지혜
detail :대행 소개 페이지 수정
=> ﻿[ks44team03] 대행 소개 페이지 수정

ks44team03/src/main/java/ks44team03/admin/controller/IncomingWarehouseManageController.java, ks44team03/src/main/java/ks44team03/admin/mapper/IncomingWarehouseManageMapper.java, ks44team03/src/main/java/ks44team03/admin/service/IncomingWarehouseManageService.java, ks44team03/src/main/java/ks44team03/dto/Nodata.java, ks44team03/src/main/resources/mapper/Incoming.xml, ks44team03/src/main/resources/mapper/Nodata.xml, ks44team03/src/main/resources/templates/incoming/goodsIncomingList.html, ks44team03/src/main/resources/templates/incoming/incomingNodata.html
author : 한효송​
detail : 버튼 눌러도 반응 없음
=> [ks44team03] 상품 도착 목록에 입고일 추가, 노데이터 입고등록 구현 중

ks44team03/src/main/resources/mapper/NoticeCenterMapper.xml, ks44team03/src/main/resources/mapper/QuestionCenterMapper.xml, ks44team03/src/main/resources/templates/couponManagementAdmin/couponAdmin.html, ks44team03/src/main/resources/templates/couponManagementAdmin/couponUserList.html, ks44team03/src/main/resources/templates/customerService/notice/noticeSearch.html
=> [ks44team03] 검색 오류 수정

ks44team03/src/main/java/ks44team03/common/controller/CustomerQuestionController.java, ks44team03/src/main/resources/templates/adminFragments/adminHeader.html, ks44team03/src/main/resources/templates/customerService/question/personalQuestionSearchAdmin.html
=> [ks44team03] admin 제거 경로 수정 완료

ks44team03/src/main/resources/templates/customerService/question/personalQuestionAnswerRegister.html
=> [ks44team03] 1:1문의 답변 등록 수정

ks44team03/src/main/java/ks44team03/common/controller/CustomerFaqController.java, ks44team03/src/main/java/ks44team03/common/controller/CustomerQuestionController.java, ks44team03/src/main/java/ks44team03/common/controller/CustomerScheduleController.java, ks44team03/src/main/resources/templates/customerService/faq/faqSearch.html, ks44team03/src/main/resources/templates/customerService/schedule/deliveryScheduleModify.html, ks44team03/src/main/resources/templates/customerService/schedule/deliveryScheduleRegister.html, ks44team03/src/main/resources/templates/customerService/schedule/deliveryScheduleSearch.html, ks44team03/src/main/resources/templates/customerService/schedule/deliveryScheduleSearchRead.html
=> [ks44team03] 자주하는질문 , 배송스케줄 경로 수정
